# Generated by Django 2.2.6 on 2020-07-21 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0004_auto_20200721_1139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='books',
        ),
    ]
